version: "3.8"

services:
  moodle:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASS: moodle
      MOODLE_URL: http://localhost:8080
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./config.php:/var/www/html/config.php
    command: bash -c "sleep 15 && /init_moodle.sh"

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db

volumes:
  db_data:
